[build]
  # Build command for React app
  command = "npm run build && netlify functions:build netlify/functions"
  # Output directory
  publish = "dist"
  # Functions directory
  functions = "netlify/functions"

[build.environment]
  # Node version for functions
  NODE_VERSION = "18"

[functions]
  # TypeScript support
  node_bundler = "esbuild"
  # Include source maps for debugging
  included_files = ["src/**/*", "netlify/functions/**/*"]

# Redirect all API requests to functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Handle client-side routing for React app
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Environment variables (will be set in Netlify dashboard)
# DATABASE_URL - PostgreSQL connection string
# JWT_SECRET - For authentication (if implementing JWT)