[build]
  # Build command for React app
  command = "npm run build && netlify functions:build --src netlify/functions"
  # Output directory
  publish = "dist"
  # Functions directory
  functions = "netlify/functions"

[build.environment]
  # Node version for functions
  NODE_VERSION = "18"

[functions]
  # TypeScript support
  node_bundler = "esbuild"
  # Include source maps for debugging
  included_files = ["src/**/*", "netlify/functions/**/*"]

# Redirect all API requests to functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Handle client-side routing for React app
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Environment variables (will be set in Netlify dashboard)
# JWT_SECRET - For authentication (if implementing JWT)

# Netlify Blob Storage configuration
[functions.environment]
  # Enable Netlify Blobs for serverless storage
  NETLIFY_BLOBS_CONTEXT = "production"

# Function-specific settings
[functions."users"]
  # Blob stores: users, leads, opportunities, staff
  included_files = ["netlify/functions/utils/**/*"]

[functions."leads"]
  included_files = ["netlify/functions/utils/**/*"]

[functions."opportunities"]
  included_files = ["netlify/functions/utils/**/*"]

[functions."staff"]
  included_files = ["netlify/functions/utils/**/*"]

# Headers for better API performance
[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"